
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: arun
  name: arun-rc
spec:
  replicas: 3
  template:
    metadata:
      name: web-app
      labels:
       app: web
    spec:
      containers:
      - name: web-app-container
        image: arun2506/arun-maven-app:2
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: arun
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port : 9999
    targetPort: 8080
    name: web-app-port
  - port : 80
    targetPort: 80
    name: nginx-port
